# Generated by Django 6.0 on 2025-12-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Namn"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beskrivning"),
                ),
                (
                    "directories",
                    models.TextField(
                        help_text="En katalog per rad, t.ex. 'dokument/', 'bilder/', 'anteckningar/'",
                        verbose_name="Kataloger",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Skapad"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Uppdaterad"),
                ),
            ],
            options={
                "verbose_name": "Mall",
                "verbose_name_plural": "Mallar",
                "ordering": ["name"],
            },
        ),
    ]
