# Generated by Django 6.0 on 2025-12-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_directory_path",
                    models.CharField(
                        default="media",
                        help_text="Absolut sökväg (t.ex. /home/user/dokument) eller relativ (t.ex. media)",
                        max_length=500,
                        verbose_name="Dokumentkatalog sökväg",
                    ),
                ),
                (
                    "media_directory_name",
                    models.CharField(
                        default="media",
                        help_text="Namnet på katalogen (används i URL)",
                        max_length=100,
                        verbose_name="Dokumentkatalog namn",
                    ),
                ),
            ],
            options={
                "verbose_name": "Systemkonfiguration",
                "verbose_name_plural": "Systemkonfiguration",
            },
        ),
    ]
