# Generated by Django 6.0 on 2026-01-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_systemconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="SetupStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Indikerar om initial setup är genomförd",
                        verbose_name="Setup klar",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="När setup slutfördes",
                        null=True,
                        verbose_name="Slutförd",
                    ),
                ),
            ],
            options={
                "verbose_name": "Setup-status",
                "verbose_name_plural": "Setup-status",
            },
        ),
    ]
