# Generated by Django 6.0 on 2026-01-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_setupstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="backup_directory_path",
            field=models.CharField(
                default="backups",
                help_text="Absolut sökväg (t.ex. /home/user/genlib-backups) eller relativ (t.ex. backups)",
                max_length=500,
                verbose_name="Backup-katalog sökväg",
            ),
        ),
    ]
