# Generated by Django 6.0 on 2026-01-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_systemconfig_backup_directory_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="image_directory_name",
            field=models.CharField(
                default="bilder",
                help_text="Namnet på underkatalogen där bilder lagras (relativ till personens katalog)",
                max_length=100,
                verbose_name="Bildkatalog namn",
            ),
        ),
    ]
