# Generated by Django 6.0 on 2026-01-08 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_systemconfig_image_directory_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemconfig",
            name="image_directory_name",
        ),
    ]
