# Generated by Django 6.0 on 2025-12-09 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Namn/ID"
                    ),
                ),
                (
                    "target_directory",
                    models.CharField(
                        help_text="Relativ sökväg, t.ex. 'dokument' eller 'dokument/födelse'",
                        max_length=200,
                        verbose_name="Målkatalog",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Standard filnamn för denna typ, t.ex. 'Sveriges befolkning 1970.txt'",
                        max_length=200,
                        verbose_name="Filnamn",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beskrivning"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Skapad"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Uppdaterad"),
                ),
            ],
            options={
                "verbose_name": "Dokumenttyp",
                "verbose_name_plural": "Dokumenttyper",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="Filnamn")),
                (
                    "file",
                    models.FileField(max_length=500, upload_to="", verbose_name="Fil"),
                ),
                (
                    "relative_path",
                    models.CharField(max_length=500, verbose_name="Relativ sökväg"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        default=0, verbose_name="Filstorlek (bytes)"
                    ),
                ),
                ("file_type", models.CharField(max_length=10, verbose_name="Filtyp")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beskrivning"),
                ),
                (
                    "source_info",
                    models.TextField(
                        blank=True,
                        help_text="VIKTIGT! T.ex. 'Riksarkivet 2024-01-15'",
                        verbose_name="Källinformation",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Kommaseparerad lista",
                        max_length=500,
                        verbose_name="Taggar",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Skapad"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Uppdaterad"),
                ),
                (
                    "file_modified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fil modifierad"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="persons.person",
                        verbose_name="Person",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.documenttype",
                        verbose_name="Dokumenttyp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokument",
                "verbose_name_plural": "Dokument",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["person", "document_type"],
                        name="documents_d_person__ec83da_idx",
                    ),
                    models.Index(
                        fields=["file_type"], name="documents_d_file_ty_1bb410_idx"
                    ),
                ],
            },
        ),
    ]
