# Generated by Django 6.0 on 2025-12-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="description",
        ),
    ]
