# Generated by Django 6.0 on 2025-12-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_remove_document_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True, max_length=500, null=True, upload_to="", verbose_name="Fil"
            ),
        ),
    ]
