# Generated by Django 6.0 on 2025-12-09 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_alter_document_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="source_info",
        ),
    ]
