# Generated by Django 6.0 on 2025-12-09 14:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Förnamn"
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Efternamn"
                    ),
                ),
                (
                    "birth_year",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Födelseår",
                    ),
                ),
                (
                    "death_year",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Dödsår",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Födelsedatum"
                    ),
                ),
                (
                    "death_date",
                    models.DateField(blank=True, null=True, verbose_name="Dödsdatum"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Anteckningar")),
                (
                    "directory_name",
                    models.CharField(max_length=200, verbose_name="Katalognamn"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Skapad"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Uppdaterad"),
                ),
                (
                    "template_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.template",
                        verbose_name="Mall använd",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Användare",
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "Personer",
                "ordering": ["surname", "firstname"],
                "indexes": [
                    models.Index(
                        fields=["surname", "firstname"],
                        name="persons_per_surname_6ee0e8_idx",
                    ),
                    models.Index(
                        fields=["directory_name"], name="persons_per_directo_16f784_idx"
                    ),
                ],
                "unique_together": {("user", "directory_name")},
            },
        ),
    ]
