# Generated by Django 6.0 on 2025-12-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="birth_year",
        ),
        migrations.RemoveField(
            model_name="person",
            name="death_year",
        ),
    ]
