# Generated by Django 6.0 on 2025-12-11 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0002_remove_person_birth_year_remove_person_death_year"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_a_to_b",
                    models.CharField(
                        choices=[
                            ("PARENT", "Förälder"),
                            ("CHILD", "Barn"),
                            ("SPOUSE", "Make/Maka"),
                            ("SIBLING", "Syskon"),
                        ],
                        max_length=20,
                        verbose_name="Relation A till B",
                    ),
                ),
                (
                    "relationship_b_to_a",
                    models.CharField(
                        choices=[
                            ("PARENT", "Förälder"),
                            ("CHILD", "Barn"),
                            ("SPOUSE", "Make/Maka"),
                            ("SIBLING", "Syskon"),
                        ],
                        max_length=20,
                        verbose_name="Relation B till A",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Anteckningar")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Skapad"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Uppdaterad"),
                ),
                (
                    "person_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_as_a",
                        to="persons.person",
                        verbose_name="Person A",
                    ),
                ),
                (
                    "person_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_as_b",
                        to="persons.person",
                        verbose_name="Person B",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Användare",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personrelation",
                "verbose_name_plural": "Personrelationer",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["person_a", "person_b"],
                        name="persons_per_person__20e716_idx",
                    ),
                    models.Index(
                        fields=["user"], name="persons_per_user_id_e3bb85_idx"
                    ),
                ],
                "unique_together": {("person_a", "person_b")},
            },
        ),
    ]
