# Generated by Django 6.0 on 2025-12-14 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0003_personrelationship"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Namn"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beskrivning"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Om aktiv synkas ändringar automatiskt till alla personer",
                        verbose_name="Aktiv",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Skapad"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Uppdaterad"),
                ),
            ],
            options={
                "verbose_name": "Checklistmall",
                "verbose_name_plural": "Checklistmallar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistTemplateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beskrivning"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("RESEARCH", "Forskning"),
                            ("DOCUMENTS", "Dokument"),
                            ("SOURCES", "Källor"),
                            ("VERIFICATION", "Verifiering"),
                            ("OTHER", "Övrigt"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Låg"),
                            ("MEDIUM", "Medel"),
                            ("HIGH", "Hög"),
                            ("CRITICAL", "Kritisk"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="Prioritet",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lägre nummer visas först",
                        verbose_name="Ordning",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Skapad"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Uppdaterad"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="persons.checklisttemplate",
                        verbose_name="Mall",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklistmallsobjekt",
                "verbose_name_plural": "Checklistmallsobjekt",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="PersonChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beskrivning"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("RESEARCH", "Forskning"),
                            ("DOCUMENTS", "Dokument"),
                            ("SOURCES", "Källor"),
                            ("VERIFICATION", "Verifiering"),
                            ("OTHER", "Övrigt"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Låg"),
                            ("MEDIUM", "Medel"),
                            ("HIGH", "Hög"),
                            ("CRITICAL", "Kritisk"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="Prioritet",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Ordning"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Avklarad"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Avklarad datum"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Personliga anteckningar för detta objekt",
                        verbose_name="Anteckningar",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Skapad"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Uppdaterad"),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="persons.person",
                        verbose_name="Person",
                    ),
                ),
                (
                    "template_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Om satt är detta synkat från mallen, annars är det anpassat",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_items",
                        to="persons.checklisttemplateitem",
                        verbose_name="Mallsobjekt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personchecklistobjekt",
                "verbose_name_plural": "Personchecklistobjekt",
                "ordering": ["person", "order", "title"],
            },
        ),
        migrations.AddIndex(
            model_name="checklisttemplateitem",
            index=models.Index(
                fields=["template", "order"], name="persons_che_templat_20b946_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checklisttemplateitem",
            index=models.Index(
                fields=["category"], name="persons_che_categor_a429af_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="checklisttemplateitem",
            unique_together={("template", "title")},
        ),
        migrations.AddIndex(
            model_name="personchecklistitem",
            index=models.Index(
                fields=["person", "is_completed"], name="persons_per_person__1eb74e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personchecklistitem",
            index=models.Index(
                fields=["person", "category"], name="persons_per_person__e43f03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personchecklistitem",
            index=models.Index(
                fields=["template_item"], name="persons_per_templat_0a0768_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personchecklistitem",
            index=models.Index(
                fields=["is_completed"], name="persons_per_is_comp_7d54f6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="personchecklistitem",
            unique_together={("person", "template_item")},
        ),
    ]
