# Generated by Django 6.0 on 2026-01-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0004_checklisttemplate_checklisttemplateitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="age",
            field=models.IntegerField(
                blank=True, help_text="Beräknad ålder", null=True, verbose_name="Ålder"
            ),
        ),
    ]
