# Generated by Django 6.0 on 2026-01-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0006_bookmarkedperson"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_main_person",
            field=models.BooleanField(
                default=False,
                help_text="Huvudperson används som standard i trädvyn",
                verbose_name="Huvudperson",
            ),
        ),
    ]
