# Generated by Django 6.0 on 2026-01-08 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_remove_document_source_info"),
        ("persons", "0007_person_is_main_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="profile_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Huvudbild för personen",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_for",
                to="documents.document",
                verbose_name="Profilbild",
            ),
        ),
    ]
